[package]
name = "chain-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
roxmltree = "0.18.0"
xmlparser = "0.13.5"
