[package]
name = "invoices-products"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
pretty_assertions = "1.3.0"
string-to-static = "0.1.0"
